'use client';

import { useState, useEffect, useCallback } from 'react';
import { LeadResponseDTO, CounselorDTO } from '@/types/api';
import { LeadService } from '@/services/leadService';
import { CounselorService } from '@/services/counselorService';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { motion, AnimatePresence } from 'framer-motion';
import { Calendar, User, Phone, Mail, Filter, RefreshCw, ChevronLeft, ChevronRight, Search } from 'lucide-react';
import toast from 'react-hot-toast';

const STATUS_COLORS: Record<string, string> = {
    NEW: 'bg-amber-100 text-amber-700 border-amber-200',
    QUEUED: 'bg-orange-100 text-orange-700 border-orange-200',
    TELECALLER_ASSIGNED: 'bg-cyan-100 text-cyan-700 border-cyan-200',
    QUALIFIED: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    COUNSELOR_ASSIGNED: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    EXTERNAL_ASSIGNED: 'bg-violet-100 text-violet-700 border-violet-200',
    ADMISSION_IN_PROCESS: 'bg-amber-100 text-amber-700 border-amber-200',
    ADMISSION_DONE: 'bg-green-100 text-green-800 border-green-200',
    LOST: 'bg-slate-100 text-slate-700 border-slate-200',
    UNASSIGNED: 'bg-gray-100 text-gray-600 border-gray-200',
    CONTACTED: 'bg-blue-100 text-blue-700 border-blue-200',
    TIMED_OUT: 'bg-rose-100 text-rose-700 border-rose-200',
    REASSIGNED: 'bg-pink-100 text-pink-700 border-pink-200',
};

export default function FakeLeadsPage() {
    const [leads, setLeads] = useState<LeadResponseDTO[]>([]);
    const [counselors, setCounselors] = useState<CounselorDTO[]>([]);
    const [selectedCounselorId, setSelectedCounselorId] = useState<number | 'all'>('all');
    const [loading, setLoading] = useState(true);
    const [counselorsLoading, setCounselorsLoading] = useState(false);
    const [totalCount, setTotalCount] = useState(0);
    const [page, setPage] = useState(0);
    const [pageSize] = useState(10);

    useEffect(() => {
        document.title = "Fake Leads Management | Admin Portal";
    }, []);

    const fetchCounselors = useCallback(async () => {
        setCounselorsLoading(true);
        try {
            const data: any = await CounselorService.getAllCounselors();
            // Handle different potential response formats
            const list: CounselorDTO[] = Array.isArray(data)
                ? data
                : data?.counselors ?? data?.data ?? data?.content ?? [];
            setCounselors(list);
        } catch (error) {
            console.error('Failed to fetch counselors:', error);
            toast.error('Could not load counselors');
        } finally {
            setCounselorsLoading(false);
        }
    }, []);

    const fetchLeads = useCallback(async () => {
        setLoading(true);
        try {
            let data: any;
            if (selectedCounselorId === 'all') {
                data = await LeadService.getFakeLeads(page, pageSize);
            } else {
                data = await LeadService.getFakeLeadsByCounselor(selectedCounselorId, page, pageSize);
            }

            setLeads(data?.fakeLeads || []);
            setTotalCount(data?.count || 0);
        } catch (error) {
            console.error('Failed to fetch fake leads:', error);
            toast.error('Could not load fake leads');
        } finally {
            setLoading(false);
        }
    }, [page, pageSize, selectedCounselorId]);

    useEffect(() => {
        fetchCounselors();
    }, [fetchCounselors]);

    useEffect(() => {
        fetchLeads();
    }, [fetchLeads]);

    const totalPages = Math.ceil(totalCount / pageSize);

    return (
        <DashboardLayout>
            <div className="min-h-screen bg-slate-50/50 p-6 lg:p-10">
                {/* Header */}
                <header className="mb-10">
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                        <motion.div
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            className="space-y-1"
                        >
                            <div className="flex items-center gap-2">

                                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                                    Fake Lead Management
                                </span>
                            </div>
                            <h1 className="text-4xl font-black text-slate-900 tracking-tight">
                                <span className="text-black-600">Fake Leads</span>
                            </h1>
                            <p className="text-slate-500 font-medium max-w-lg">
                                THIS IS FAKE LEAD OR LOST GENERATED BY COUNSELOR OR ADMIN
                            </p>
                        </motion.div>

                        <div className="flex items-center gap-3">
                            <motion.button
                                whileHover={{ scale: 1.02 }}
                                whileTap={{ scale: 0.98 }}
                                onClick={() => fetchLeads()}
                                disabled={loading}
                                className="flex items-center gap-2 px-5 py-3 rounded-2xl bg-white text-slate-700 text-[10px] font-black uppercase tracking-widest border border-slate-200 shadow-sm hover:border-rose-200 transition-all disabled:opacity-50"
                            >
                                <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />

                            </motion.button>
                        </div>
                    </div>
                </header>

                {/* Filters */}
                <div className="mb-8 grid grid-cols-1 lg:grid-cols-4 gap-6">
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="lg:col-span-3 bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col sm:flex-row items-end gap-6"
                    >
                        <div className="flex-1 w-full space-y-2">
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1 flex items-center gap-2">
                                <Filter className="w-3 h-3 text-rose-500" />
                                Filter by Counselor
                            </label>
                            <div className="relative">
                                <select
                                    value={selectedCounselorId}
                                    onChange={(e) => {
                                        const val = e.target.value;
                                        setSelectedCounselorId(val === 'all' ? 'all' : Number(val));
                                        setPage(0);
                                    }}
                                    disabled={counselorsLoading}
                                    className="w-full h-12 pl-4 pr-10 bg-slate-50 border border-slate-200 rounded-2xl text-xs font-bold text-slate-700 appearance-none focus:outline-none focus:ring-2 focus:ring-rose-500/10 focus:border-rose-300 transition-all cursor-pointer"
                                >
                                    <option value="all">All Counselors (Overview)</option>
                                    {counselors.map((c) => (
                                        <option key={c.counselorId} value={c.counselorId}>
                                            {c.name} — {c.counselorTypes?.join(', ')}
                                        </option>
                                    ))}
                                </select>
                                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                                    <ChevronRight className="w-4 h-4 rotate-90" />
                                </div>
                            </div>
                        </div>

                        <div className="w-full sm:w-auto p-4 bg-rose-50 rounded-2xl border border-rose-100 flex flex-col items-center justify-center">
                            <p className="text-[9px] font-black text-rose-400 uppercase tracking-widest">Total Results</p>
                            <p className="text-xl font-black text-rose-700">{totalCount}</p>
                        </div>
                    </motion.div>
                </div>

                {/* Table Content */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="bg-white rounded-[32px] border border-slate-100 shadow-xl overflow-hidden min-h-[500px] flex flex-col"
                >
                    <div className="overflow-x-auto">
                        <table className="w-full text-left">
                            <thead className="bg-slate-50/50 border-b border-slate-100">
                                <tr>
                                    <th className="px-8 py-5 text-[10px] font-black uppercase text-slate-400 tracking-widest">Lead Identity</th>
                                    <th className="px-8 py-5 text-[10px] font-black uppercase text-slate-400 tracking-widest">Contact Information</th>
                                    <th className="px-8 py-5 text-[10px] font-black uppercase text-slate-400 tracking-widest">Assigned Course</th>
                                    <th className="px-8 py-5 text-[10px] font-black uppercase text-slate-400 tracking-widest">Current Status</th>
                                    <th className="px-8 py-5 text-[10px] font-black uppercase text-slate-400 tracking-widest text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-50">
                                <AnimatePresence mode="wait">
                                    {loading ? (
                                        <motion.tr
                                            key="loading"
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            exit={{ opacity: 0 }}
                                        >
                                            <td colSpan={5} className="py-32 text-center">
                                                <div className="flex flex-col items-center gap-4">
                                                    <div className="relative w-12 h-12">
                                                        <div className="absolute inset-0 border-4 border-rose-100 rounded-full" />
                                                        <div className="absolute inset-0 border-4 border-rose-600 rounded-full border-t-transparent animate-spin" />
                                                    </div>
                                                    <div className="space-y-1">
                                                        <p className="text-[10px] font-black text-rose-600 uppercase tracking-widest">Synchronizing</p>
                                                        <p className="text-xs font-bold text-slate-400 italic">Extracting simulated data streams...</p>
                                                    </div>
                                                </div>
                                            </td>
                                        </motion.tr>
                                    ) : leads.length === 0 ? (
                                        <motion.tr
                                            key="empty"
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            exit={{ opacity: 0 }}
                                        >
                                            <td colSpan={5} className="py-32 text-center">
                                                <div className="flex flex-col items-center gap-4">
                                                    <div className="w-16 h-16 bg-slate-50 rounded-3xl flex items-center justify-center text-slate-200 border border-slate-100">
                                                        <Search className="w-8 h-8" />
                                                    </div>
                                                    <p className="text-sm font-bold text-slate-400 italic">No fake leads found in the system</p>
                                                </div>
                                            </td>
                                        </motion.tr>
                                    ) : (
                                        leads.map((lead, idx) => (
                                            <motion.tr
                                                key={lead.id}
                                                initial={{ opacity: 0, y: 10 }}
                                                animate={{ opacity: 1, y: 0 }}
                                                transition={{ delay: idx * 0.05 }}
                                                className="group hover:bg-slate-50/50 transition-all cursor-default"
                                            >
                                                <td className="px-8 py-6">
                                                    <div className="flex items-center gap-4">
                                                        <div className="w-10 h-10 rounded-2xl bg-rose-50 border border-rose-100 flex items-center justify-center text-rose-600 font-black text-xs">
                                                            {lead.name?.charAt(0) || '?'}
                                                        </div>
                                                        <div>
                                                            <div className="font-black text-slate-800 text-sm group-hover:text-rose-600 transition-colors uppercase tracking-tight">{lead.name || 'Anonymous'}</div>
                                                            <div className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-0.5 mt-1 border border-slate-100 rounded-md px-1.5 py-0.5 bg-white w-fit">Ref: #{lead.id}</div>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-8 py-6">
                                                    <div className="space-y-1.5">
                                                        <div className="flex items-center gap-2 text-xs font-bold text-slate-600">
                                                            <Phone className="w-3 h-3 text-slate-400" />
                                                            {lead.phone || 'No Phone'}
                                                        </div>
                                                        <div className="flex items-center gap-2 text-xs font-medium text-slate-400">
                                                            <Mail className="w-3 h-3 text-slate-300" />
                                                            {lead.email || 'No Email'}
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-8 py-6">
                                                    <div className="inline-flex flex-col">
                                                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Academic Path</span>
                                                        <span className="text-xs font-bold text-slate-700 bg-slate-100 px-2.5 py-1 rounded-lg border border-slate-200">
                                                            {typeof lead.course === 'object' ? lead.course.course : lead.course || 'Unspecified'}
                                                        </span>
                                                    </div>
                                                </td>
                                                <td className="px-8 py-6">
                                                    <span className={`px-3 py-1 rounded-full text-[9px] font-black tracking-widest uppercase border shadow-sm ${STATUS_COLORS[lead.status] || 'bg-slate-50 text-slate-500 border-slate-200'}`}>
                                                        {lead.status?.replace(/_/g, ' ') || 'UNKNOWN'}
                                                    </span>
                                                </td>
                                                <td className="px-8 py-6 text-right">
                                                    <button className="px-4 py-2 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-rose-600 transition-all shadow-lg shadow-slate-900/10 hover:shadow-rose-600/20 active:scale-95">
                                                        Inspect
                                                    </button>
                                                </td>
                                            </motion.tr>
                                        ))
                                    )}
                                </AnimatePresence>
                            </tbody>
                        </table>
                    </div>

                    {/* Pagination */}
                    <div className="mt-auto px-8 py-6 bg-slate-50/50 border-t border-slate-100 flex items-center justify-between">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                            {loading ? 'Processing...' : `Displaying ${leads.length} of ${totalCount} entries`}
                        </p>

                        <div className="flex items-center gap-4">
                            <div className="flex gap-2">
                                <button
                                    onClick={() => setPage(p => Math.max(0, p - 1))}
                                    disabled={page === 0 || loading}
                                    className="w-10 h-10 flex items-center justify-center border border-slate-200 rounded-xl bg-white text-slate-500 hover:border-rose-300 hover:text-rose-600 transition-all disabled:opacity-30 disabled:hover:border-slate-200 disabled:hover:text-slate-500"
                                >
                                    <ChevronLeft className="w-4 h-4" />
                                </button>

                                <div className="px-5 flex items-center justify-center h-10 bg-white border border-slate-200 rounded-xl text-[10px] font-black text-slate-600 uppercase tracking-widest shadow-sm">
                                    Page {page + 1} <span className="mx-2 text-slate-300">/</span> {totalPages || 1}
                                </div>

                                <button
                                    onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))}
                                    disabled={page >= totalPages - 1 || loading}
                                    className="w-10 h-10 flex items-center justify-center border border-slate-200 rounded-xl bg-white text-slate-500 hover:border-rose-300 hover:text-rose-600 transition-all disabled:opacity-30 disabled:hover:border-slate-200 disabled:hover:text-slate-500"
                                >
                                    <ChevronRight className="w-4 h-4" />
                                </button>
                            </div>
                        </div>
                    </div>
                </motion.div>

                {/* Info Card */}
                <div className="mt-10 p-6 bg-gradient-to-br from-indigo-900 to-indigo-950 rounded-[32px] text-white overflow-hidden relative shadow-2xl">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -translate-y-32 translate-x-32 blur-3xl pointer-events-none" />
                    <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-8">
                        <div className="space-y-2">
                            <h3 className="text-xl font-black tracking-tight">System Notice: Fake Data Generation</h3>
                            <p className="text-indigo-200 text-sm font-medium max-w-2xl">
                                This environment automatically populates filtered views with synthetic data when requested.
                                Click "Sync Data" to regenerate or refresh the current view.
                            </p>
                        </div>
                        <div className="bg-white/10 backdrop-blur-md px-6 py-4 rounded-2xl border border-white/10 flex items-center gap-4 group hover:bg-white/20 transition-all cursor-default w-full md:w-auto">
                            <Calendar className="w-8 h-8 text-rose-400" />
                            <div>
                                <p className="text-[10px] font-black text-indigo-300 uppercase tracking-widest">Active Session</p>
                                <p className="text-sm font-bold">{new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
